{"name": "Проверяем что упадет ошибка при попытки логина несуществующего курьера", "status": "passed", "start": 1701882089070, "stop": 1701882089203, "uuid": "1433c3d6-5281-40a1-8c6b-ab74e84ff09f", "historyId": "43379f67c127106016bab83f2e020344", "testCaseId": "43379f67c127106016bab83f2e020344", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "b-ibragimov"}, {"name": "thread", "value": "75040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}