{"name": "Проверяем что упадет ошибка при попытки создания курьера который уже есть в системе", "status": "passed", "start": 1701882087080, "stop": 1701882087266, "uuid": "2473a219-6c75-4a94-a842-861c0e37532f", "historyId": "acabbc76923b821a85254480483a69ee", "testCaseId": "acabbc76923b821a85254480483a69ee", "fullName": "tests.test_create_courier.TestCreateCourier#test_check_create_identical_couriers", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "b-ibragimov"}, {"name": "thread", "value": "75040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}